// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh_PATj7n5TRxynxL09CyGgurie1RgBZI',
    appId: '1:381096331282:web:90e64eeeae567ccde170cb',
    messagingSenderId: '381096331282',
    projectId: 'lumbunghedera-test',
    authDomain: 'lumbunghedera-test.firebaseapp.com',
    storageBucket: 'lumbunghedera-test.appspot.com',
    measurementId: 'G-TN8S06F9RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbZJHKtvFcVLClOg_Bfys79oBqGzY_QNw',
    appId: '1:381096331282:android:fd538a1c3316b616e170cb',
    messagingSenderId: '381096331282',
    projectId: 'lumbunghedera-test',
    storageBucket: 'lumbunghedera-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBur2cI5F1_q75A4GjpZfWnMs9Mb6gKbpg',
    appId: '1:381096331282:ios:33454d406dab4367e170cb',
    messagingSenderId: '381096331282',
    projectId: 'lumbunghedera-test',
    storageBucket: 'lumbunghedera-test.appspot.com',
    iosClientId: '381096331282-u55a5etmjj7h5is794dd5qebv94tdud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumbunghederaDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBur2cI5F1_q75A4GjpZfWnMs9Mb6gKbpg',
    appId: '1:381096331282:ios:33454d406dab4367e170cb',
    messagingSenderId: '381096331282',
    projectId: 'lumbunghedera-test',
    storageBucket: 'lumbunghedera-test.appspot.com',
    iosClientId: '381096331282-u55a5etmjj7h5is794dd5qebv94tdud4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumbunghederaDashboard',
  );
}
