// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7J0LiKEnLNnvo4JGFwWHbOdCZfsLhnh8',
    appId: '1:439332822960:web:06e0e43a2ce060a848c075',
    messagingSenderId: '439332822960',
    projectId: 'lumbungalgo',
    authDomain: 'lumbungalgo.firebaseapp.com',
    storageBucket: 'lumbungalgo.appspot.com',
    measurementId: 'G-VBL24J3R82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlrlptgQG3ibAJ0PJdJ_cLNeYxMmBerI',
    appId: '1:439332822960:android:24b13ea3392fc25148c075',
    messagingSenderId: '439332822960',
    projectId: 'lumbungalgo',
    storageBucket: 'lumbungalgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zz8ztp3oI6xFlyfydXtgLdD79W5_dnQ',
    appId: '1:439332822960:ios:3959e5ea808a01f548c075',
    messagingSenderId: '439332822960',
    projectId: 'lumbungalgo',
    storageBucket: 'lumbungalgo.appspot.com',
    iosClientId:
        '439332822960-bji7t2cnr5lqak3kqll3htkc00vi6jsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumbungWalletCai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zz8ztp3oI6xFlyfydXtgLdD79W5_dnQ',
    appId: '1:439332822960:ios:3959e5ea808a01f548c075',
    messagingSenderId: '439332822960',
    projectId: 'lumbungalgo',
    storageBucket: 'lumbungalgo.appspot.com',
    iosClientId:
        '439332822960-bji7t2cnr5lqak3kqll3htkc00vi6jsj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumbungWalletCai',
  );
}
